Modules/Role/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Role\Http\Controllers\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::resource('role', RoleController::class)->names('role');
    Route::get('role/{id}/destroy', [RoleController::class, 'destroy'])->name('role.destroy');
    Route::get('role/{id}/give_permission', [RoleController::class, 'add_permission'])->name('role.add_permission');
    Route::post('role/{id}/give_permission', [RoleController::class, 'give_permission'])->name('role.give_permission');
});

Modules/Role/app/Http/Controllers/RoleController.php
<?php

namespace Modules\Role\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Role::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '';
                    if(auth()->user()->can('give permission')){
                        $btn = '<a href="'.route('role.add_permission', $row->id).'" class="edit btn btn-primary btn-sm">Tambahkan Permission <i class="fa fa-lock"></i></a>';
                    }
                    $btn .= '&nbsp;&nbsp;';

                    if(auth()->user()->can('edit role')){
                    $btn .= '<a href="'.route('role.edit', $row->id).'" class="edit btn btn-warning btn-sm">Edit <i class="fa fa-edit"></i></a>';
                    }
                    $btn .= '&nbsp;&nbsp;';

                    if(auth()->user()->can('delete role')){
                    $btn .= ' <a href="'.route('role.destroy', $row->id).'" class="delete btn btn-danger btn-sm">Delete <i class="fa fa-trash"></i></a>';
                    }
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('role::index');
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('role::create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'role_name' => 'required','string','unique:roles,name',
        ]);

        Role::create([
            'name' => $request->input('role_name'),
        ]);

        return redirect()->route('role.index')->with('success', 'Role created successfully.');
    }

    /**
     * Show the specified resource.
     */
    public function show($id)
    {
        return view('role::show');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $role = Role::find($id);
        return view('role::edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id): RedirectResponse
    {
        $request->validate([
            'role_name' => 'required','string','unique:roles,name,',
        ]);

        $role = Role::find($id);
        $role->name = $request->input('role_name');
        $role->save();

        return redirect()->route('role.index')->with('success', 'Role updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        $role->delete();
        return redirect()->route('role.index')->with('success', 'Role deleted successfully.');
    }

    public function add_permission($id) 
    {
        $role = Role::find($id);
        $permissions = Permission::all();
        $rolePermissions = DB::table('role_has_permissions')
                                ->where('role_has_permissions.role_id', $role->id)
                                ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
                                ->all();
        return view('role::add_permission', compact('role', 'permissions', 'rolePermissions'));
    }

    public function give_permission(Request $request, $id)
    {
        $request->validate([
            'permission' => 'required|array',
        ]);

        $role = Role::find($id);

        $rolePermissions = $role->permissions->pluck('id')->toArray();

        $newPermissions = $request->input('permission');

        $permissionsToAdd = array_diff($newPermissions, $rolePermissions);
        if (!empty($permissionsToAdd)) {
            $permissions = Permission::whereIn('id', $permissionsToAdd)->get();
            $role->givePermissionTo($permissions);
        }

        $permissionsToRemove = array_diff($rolePermissions, $newPermissions);
        if (!empty($permissionsToRemove)) {
            $permissions = Permission::whereIn('id', $permissionsToRemove)->get();
            $role->revokePermissionTo($permissions);
        }

        return redirect()->route('role.index')->with('success', 'Permission updated successfully.');
    }


}

Modules/Role/resources/views/add_permission.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Role Update</h1>
        <a href="{{route('role.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <div class="form-group">
                <label for="">Role Name</label>
                <input type="text" class="form-control" value="{{$role->name}}" name="role_name" readonly>
            </div>
            <form action="{{route('role.give_permission', $role->id)}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="">Permission</label>
                    <div class="row">
                        @foreach ($permissions as $permission)
                        <div class="col-md-2">
                            <label>
                                <input type="checkbox" name="permission[]" value="{{ $permission->id }}"
                                    {{ in_array($permission->id, $rolePermissions) ? 'checked':'' }} />
                                {{ $permission->name }}
                            </label>
                        </div>
                        @endforeach
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endsection

Modules/Role/resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Role Create</h1>
        <a href="{{route('role.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('role.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="">Role Name</label>
                    <input type="text" class="form-control" name="role_name">
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Role/resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Role Update</h1>
        <a href="{{route('role.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('role.update', $role->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Role Name</label>
                    <input type="text" class="form-control" value="{{$role->name}}" name="role_name">
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Role/resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Role</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h4>Role Table</h4>
                    @can('create role')
                    <a href="{{route('role.create')}}" class="btn btn-success">Add Role <i class="fas fa-plus"></i></a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-bordered" id="table_data">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Role Name</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $('#table_data').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('role.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: '#'},
                {data: 'name', name: 'name'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        })
    })
</script>
@endsection