Modules/Cabang/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Cabang\Http\Controllers\CabangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::resource('cabang', CabangController::class)->names('cabang');
    Route::get('cabang/{id}/destroy', [CabangController::class, 'destroy'])->name('cabang.destroy');
    Route::get('cabang/{id}/detail_outlet', [CabangController::class, 'detail_outlet'])->name('cabang.detail_outlet');
});

Modules/Cabang/app/Models/CabangM.php
<?php

namespace Modules\Cabang\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Cabang\Database\factories\CabangMFactory;

class CabangM extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'id','admin_id','outlet_name','address','created_at','updated_at'
    ];
    protected $table = 'cabang';
    
    public function admin()
    {
        return $this->belongsTo(User::class);
    }
}

Modules/Cabang/app/Http/Controllers/CabangController.php
<?php

namespace Modules\Cabang\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Cabang\Models\CabangM;

class CabangController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if($request->ajax())
        {
            $data = CabangM::latest()->get();
            return datatables()->of($data)
                ->addIndexColumn()
                ->addColumn('admin', function($data){
                    $admin = $data->admin->name;
                    return $admin;
                })
                ->addColumn('action', function($data){
                    $btn = '';
                    $btn = '<a href="'.route('cabang.detail_outlet', $data->id).'" data-toggle="tooltip"  data-id="'.$data->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm">Detail</a>';
                    $btn .= '&nbsp;&nbsp;';
                    if(auth()->user()->can('edit cabang')){
                        $btn .= '<a href="'.route('cabang.edit', $data->id).'" data-toggle="tooltip"  data-id="'.$data->id.'" data-original-title="Edit" class="edit btn btn-warning btn-sm editCabang">Edit</a>';
                    }
                    $btn .= '&nbsp;&nbsp;';
                    if(auth()->user()->can('delete cabang')){
                        $btn = $btn.' <a href="'.route('cabang.destroy', $data->id).'" data-toggle="tooltip"  data-id="'.$data->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteCabang">Delete</a>';
                    }
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('cabang::index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $user = User::whereHas('roles',function($q){
            $q->where('name','admin');
        })->get();
        return view('cabang::create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'outlet_name' => 'required',
            'admin_id' => 'required','exists:users,id','unique:cabang,admin_id',
            'address' => 'required',
        ]);

        CabangM::create([
            'outlet_name' => $request->outlet_name,
            'admin_id' => $request->admin_id,
            'address' => $request->address,
        ]);

        return redirect()->route('cabang.index')->with('success', 'Cabang created successfully.');
    }

    /**
     * Show the specified resource.
     */
    public function show($id)
    {
        return view('cabang::show');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $cabang = CabangM::find($id);
        $user = User::whereHas('roles',function($q){
            $q->where('name','admin');
        })->get();
        return view('cabang::edit', compact('cabang', 'user'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id): RedirectResponse
    {
        $request->validate([
            'outlet_name' => 'required',
            'admin_id' => 'required','exists:users,id','unique:cabang,admin_id',
            'address' => 'required',
        ]);

        CabangM::find($id)->update([
            'outlet_name' => $request->outlet_name,
            'admin_id' => $request->admin_id,
            'address' => $request->address,
        ]);

        return redirect()->route('cabang.index')->with('success', 'Cabang updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $cabang = CabangM::find($id);
        $cabang->delete();
        return redirect()->route('cabang.index')->with('success', 'Cabang deleted successfully.');
    }

    public function detail_outlet($id)
    {
        $cabang = CabangM::find($id);
        return view('cabang::detail_cabang', compact('cabang'));
    }
}

Modules/Cabang/resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Outlet Create</h1>
        <a href="{{route('cabang.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('cabang.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="">Outlet Name</label>
                    <input type="text" class="form-control" name="outlet_name">
                </div>
                <div class="form-group">
                    <label for="">Admin Name</label>
                    <select name="admin_id" id="" class="form-control">
                        <option value="">Select Admin</option>
                        @foreach ($user as $item)
                        <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Address Outlet</label>
                    <textarea name="address" id="" cols="30" rows="10" class="form-control"></textarea>
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Cabang/resources/views/detail_cabang.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Outlet - {{$cabang->outlet_name}}</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h4>Outlet Detail</h4>
                    <a href="{{route('cabang.index')}}" class="btn btn-primary">Laporan Penjualan PDF  <i class="fas fa-download"></i></a>
                </div>
                <div class="card-body">
                    <div class="mb-2">
                        <p class="m-0">Admin Name : {{$cabang->admin->name}}</p>
                        <p class="m-0">Address : {{$cabang->address}}</p>
                        <a href="" class="btn btn-primary">Stock Barang</a>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <input type="text" class="form-control" name="search" onchange="filteringdata(this)" id="search" placeholder="Search...">
                        <span class="btn btn-primary input-group-text" onclick="window.location='{{route('cabang.index')}}'"><i class="fas fa-times text-white"></i></span>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Product Terjual</th>
                                <th scope="col">Qty</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</section>
@endsection

Modules/Cabang/resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Outlet Create</h1>
        <a href="{{route('cabang.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('cabang.update', $cabang->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Outlet Name</label>
                    <input type="text" class="form-control" name="outlet_name" value="{{$cabang->outlet_name}}">
                </div>
                <div class="form-group">
                    <label for="">Admin Name</label>
                    <select name="admin_id" id="" class="form-control">
                        <option value="">Select Admin</option>
                        @foreach ($user as $item)
                        <option value="{{$item->id}}" {{ $cabang->admin_id == $item->id ? 'selected':'' }}>{{$item->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Address Outlet</label>
                    <textarea name="address" id="" cols="30" rows="10" class="form-control" >{{$cabang->address}}</textarea></textarea>
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Cabang/resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Outlet</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h4>Outlet Table</h4>
                    @can('create cabang')
                    <a href="{{route('cabang.create')}}" class="btn btn-success">Add Outlet <i
                            class="fas fa-plus"></i></a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-bordered" id="cabang-table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Outlet Name</th>
                                <th scope="col">Admin Name</th>
                                <th scope="col">Address</th>
                                {{-- <th scope="col">Income/Month</th> --}}
                                {{-- <th scope="col">Count Product</th> --}}
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</section>
<script>
    $(document).ready(function() {
        $('#cabang-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('cabang.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'outlet_name', name: 'outlet_name'},
                {data: 'admin', name: 'admin'},
                {data: 'address', name: 'address'},
                // {data: 'income', name: 'income'},
                // {data: 'count_product', name: 'count_product'},
                {data: 'action', name: 'action'},
            ]
        })
    })
</script>
@endsection