Modules/Permission/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Permission\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::resource('permission', PermissionController::class)->names('permission');
    Route::get('permission/{id}/destroy', [PermissionController::class, 'destroy'])->name('permission.destroy');
});

Modules/Permission/app/Http/Controllers/PermissionController.php
<?php

namespace Modules\Permission\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Spatie\Permission\Models\Permission;
use Yajra\DataTables\Facades\DataTables;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $data = Permission::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $btn = '';
                    if(auth()->user()->can('edit permission')){
                        $btn = '<a href="'.route('permission.edit', $row->id).'" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editPermission">Edit</a>';
                    }
                    $btn .= '&nbsp;&nbsp;';

                    if(auth()->user()->can('delete permission')){
                    $btn = $btn.' <a href="'.route('permission.destroy', $row->id).'" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deletePermission">Delete</a>';
                    }
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('permission::index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('permission::create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request) : RedirectResponse
    {
        $request->validate([
            'permission_name' => 'required','string','unique:permissions,name',
        ]);

        Permission::create([
            'name' => $request->input('permission_name'),
        ]);

        return redirect()->route('permission.index')->with('success', 'Permission created successfully.');
    }

    /**
     * Show the specified resource.
     */
    public function show($id)
    {
        return view('permission::show');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $permission = Permission::find($id);
        return view('permission::edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'permission_name' => 'required','string','unique:permissions,name',
        ]);

        $permission = Permission::find($id);
        $permission->name = $request->input('permission_name');
        $permission->save();

        return redirect()->route('permission.index')->with('success', 'Permission created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $permission = Permission::find($id);
        $permission->delete();
        return redirect()->route('permission.index')->with('success', 'Permission deleted successfully.');
    }
}

Modules/Permission/resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Permission Create</h1>
        <a href="{{route('permission.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('permission.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="">Permission Name</label>
                    <input type="text" class="form-control" name="permission_name">
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Permission/resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header justify-content-between">
        <h1>Permission Update</h1>
        <a href="{{route('permission.index')}}" class="btn btn-primary">Back <i class="fas fa-arrow-left"></i></a>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <form action="{{route('permission.update', $permission->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Permission Name</label>
                    <input type="text" class="form-control" value="{{$permission->name}}" name="permission_name">
                </div>
                <button class="btn btn-primary" type="submit">Submit <i class="fas fa-paper-plane"></i></button>
            </form>
        </div>
    </div>
</section>
@endSection

Modules/Permission/resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Permission</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h4>Permission Table</h4>
                    @can('create permission')
                    <a href="{{route('permission.create')}}" class="btn btn-success">Add Permission <i class="fas fa-plus"></i></a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-bordered" id="table_data">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Permission Name</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</section>
<script>
    $(document).ready(function() {
        $('#table_data').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('permission.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: '#'},
                {data: 'name', name: 'name'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        })
    })
</script>
@endsection